### PR TITLE
Add package manager installation instructions to the right bar

### PR DESCRIPTION
**Pull request by msavy**
image

Thoughts?

### CODE REVIEW

**Comment by adinn** [comment]
Looks good but how about changing the title from Install Byteman to Quick Install

**Comment by msavy** [comment]
That’s what I had initially but couldn’t quite decide what looked best. Shall change it back.

**Comment by adinn** [comment]
Ha!

**Comment by adinn** [comment]
Yeah, let's go with Quick Install

**Comment by msavy** [comment]
Done!

**Pull request merged**
